name: SFTP Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    uses: actions/checkout@v3
    uses: Dylan700/sftp-upload-action@latest
    with:
      server: 164.92.81.73
      username: thisanimus
      key: ${{secrets.PRIVATE_KEY}}
      port: 22
      uploads: |
        ./ => /var/www/labs.thisanimus.com/