name: 🚀 Deploy website on push

on:
  push:
    branches: [main]

jobs:
  deploy_job:
  runs-on: ubuntu-latest
  name: deploy
  steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    - name: 🎉 Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: 'thisanumus'
        server: 164.92.81.73
        ssh_private_key: ${{ secrets.PRIVATE_KEY }}
        local_path: './*'
        remote_path: '/var/www/labs.thisanimus.com'
        sftpArgs: '-o ConnectTimeout=5'
